Added the new DQ_SerialManipulatorMDH() Class
dqrobotics/cpp pull request #35
Opened 2022-01-18 01:15 UTC by juanjqo

Hi @mmmarinho, 

As discussed internally, I included C++ support for the new DQ_SerialManipulatorMDH(). This class enables kinematic modeling of serial manipulators using the modified DH convention.

2022-01-18 13:20 UTC, mmmarinho requested changes
@juanjqo 
Requesting changes (mainly):
- Fixes in small details in the headers.
- Documentation
See attached detailed comments.

2022-01-18 13:20 UTC, mmmarinho commented on include/dqrobotics/robot_modeling/DQ_SerialManipulatorMDH.h
> +(C) Copyright 2020 DQ Robotics Developers
Please update to 2022.

2022-01-18 13:20 UTC, mmmarinho commented on include/dqrobotics/robot_modeling/DQ_SerialManipulatorMDH.h
> +    DEPRECATED DQ_SerialManipulatorMDH(const MatrixXd& dh_matrix, const std::string&);
We don't need this deprecation for `DQ_SerialManipulatorMDH`, because it is a new class.

2022-01-18 13:20 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> +(C) Copyright 2020 DQ Robotics Developers
2022

2022-01-18 13:20 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> +DQ DQ_SerialManipulatorMDH::_get_w(const int &ith) const
Documentation

2022-01-18 17:07 UTC, juanjqo commented
@mmmarinho I did the requested modifications. :smiley:

2022-01-20 13:48 UTC, mmmarinho requested changes
@juanjqo 
Just a few extra changes and we are good to go!

2022-01-20 13:48 UTC, mmmarinho commented on include/dqrobotics/robot_modeling/DQ_SerialManipulatorMDH.h
> +    DQ _dh2dq(const double& q, const int& ith) const;
Just a minor comment here because I have other comments in the `.cpp` as well.
Maybe best to change the signature to
`_mdh2dq`.

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @returns None
If a method doesn't return anything (which applies for all constructors in CPP), you can remove this line.

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @param None.
You can remove the `@param` if there are no parameters.

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @param None.
Remove this

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @param None.
Remove this

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @param None.
Remove this

2022-01-20 13:48 UTC, mmmarinho commented on src/robot_modeling/DQ_SerialManipulatorMDH.cpp
> + * @param None.
Remove this

2022-01-20 14:25 UTC, juanjqo commented on include/dqrobotics/robot_modeling/DQ_SerialManipulatorMDH.h
> +    DQ _dh2dq(const double& q, const int& ith) const;
I agree with your suggestion. I think is better. 
In addition to _dh2dq (Now _mdh2dq), I modified the parameters dh_matrix_ to mdh_matrix_. 
What do you think?

2022-01-20 14:45 UTC, mmmarinho approved these changes

2022-01-20 14:46 UTC, merged