Implement methods for matrices Q4 and Q8.
dqrobotics/cpp pull request #56
Opened 2022-12-23 17:48 UTC by marcos-pereira

The methods namespace functions for Q4 and Q8 were added. The DQ class methods for Q4 and Q8 were added. 

I compared the output of the methods with the [Matlab implementation](https://github.com/dqrobotics/matlab/blob/master/%40DQ/Q8.m), but I did not test them extensively as mentioned in #55. Testing is still to be done.

2022-12-24 05:02 UTC, juanjqo commented
Hi @marcos-pereira, thank your for your PR. I'm going to implement the tests. I'll let you know  if additional modifications are required. Please check these [guidelines](https://github.com/dqrobotics/matlab/blob/master/CONTRIBUTING.md), especially the part related to the commit messages.

Best regards, 

Juancho

2022-12-24 14:16 UTC, marcos-pereira commented
Hi @juanjqo , should I edit my commit message? Or do you think I should wait for you to implement the tests first? 

I would also propose that you guys put a link to the [contributing guidelines](https://github.com/dqrobotics/matlab/blob/master/CONTRIBUTING.md) somewhere more visible in the main pages of the DQ robotics repository or in the [DQ robotics page](https://dqrobotics.github.io/). Before opening the pull request, I searched for some guidelines but did not find them on the main page or on the C++ repository.

Let me know the next steps to continue the PR.

Best regards,
Marcos

2022-12-26 01:31 UTC, juanjqo commented
Hi @marcos-pereira, 

you can update the message. I'm still working on other tasks. 
Concerning the guidelines for C++, we are actually working on it right now. The [CONTRIBUTING.md](https://github.com/dqrobotics/matlab/blob/master/CONTRIBUTING.md) file was added only in `dqrobotics/matlab`. However, both `dqrobotics/cpp` and  `dqrobotics/python` will have similar guidelines. 
Either way, we need to update the [documentation](https://dqroboticsgithubio.readthedocs.io/en/latest/).

Best regards, 

Juancho

2022-12-26 12:20 UTC, marcos-pereira commented
Hello @juanjqo ,

I amended my PR commit message, but I did not change the PR title. Should I change also the PR title? Could you check if my amend is correct?

Best,
Marcos

2022-12-27 12:37 UTC, juanjqo commented
Hi @marcos-pereira, the amend looks good.

2023-01-04 05:44 UTC, mmmarinho commented
@marcos-pereira @juanjqo 
I'll convert this to a draft and you can convert it back when you're ready to get it reviewed/tested.

2023-01-17 14:40 UTC, marcos-pereira commented
Hello @juanjqo , any updates on the tests for this PR? Can I help with something?

2023-01-18 02:46 UTC, juanjqo commented
> Hello @juanjqo , any updates on the tests for this PR? Can I help with something?

Hi @marcos-pereira, thank you. I already implemented the tests. I'm just waiting for the [modifications](https://github.com/dqrobotics/cpp/pull/56#issuecomment-1365872195) I request you to implement.

2023-01-18 14:46 UTC, marcos-pereira commented
Hello @juanjqo I have amended my commit message in my last two commits. I will mark the PR as Ready for review. 
Let me know if there is still any additional step I must do.

2023-01-20 03:49 UTC, juanjqo requested changes

2023-01-20 19:23 UTC, marcos-pereira commented on src/DQ.cpp
> +/** Return the partial derivative of the unit quaternion r with respect to log(r)
Hello @juanjqo , I did the amendments and pushed them.

2023-01-20 19:24 UTC, marcos-pereira commented on src/DQ.cpp
> + * Return the partial derivative of the unit dual quaternion x with respect to log(x)
@juanjqo , done accordingly with the [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/dafa5c819889ac57811e3954434426099de0b3a9).

2023-01-20 19:25 UTC, marcos-pereira commented on src/DQ.cpp
> +        throw(std::range_error("Bad translation() call: Not a unit dual quaternion"));
@juanjqo , done in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/dafa5c819889ac57811e3954434426099de0b3a9).

2023-01-20 19:39 UTC, marcos-pereira commented on src/DQ.cpp
> +- Marcos da Silva Pereira (marcos.si.pereira@gmail.com)
Hi @juanjqo , I opened the discussion and read some of it (it was quite long). Could you please summarize the conclusion of it shortly? From what I read, I think this PR does not count as a full contribution, because I simply translated the Q4 and Q8 from Matlab to C++. 

If you could specify the changes I must do regarding the contribution, it would be great.

2023-01-20 19:47 UTC, bvadorno commented on src/DQ.cpp
> +- Marcos da Silva Pereira (marcos.si.pereira@gmail.com)
Hi @marcos-pereira,

The contribution can be something like "Marcos Pereira: Translated the Q4 and Q8 methods from the MATLAB implementation." (Adjust the text to comply with the style that @juanjqo mentioned.)

Regarding the discussion that @juanjqo pointed out, you must read it in full, and you should not rely on people to digest things for you. Otherwise, it would be easier for them to implement the requested functionalities themselves. Recall that the development of DQ Robotics is voluntary work, and if you want your contribution to be included, you need to add value to the development workflow and make it as easy as possible for the development team.

Kind regards,
Bruno

2023-01-20 20:00 UTC, marcos-pereira commented on src/DQ.cpp
> +- Marcos da Silva Pereira (marcos.si.pereira@gmail.com)
Hi @bvadorno , sorry for the misunderstanding. I read the specific comment discussion now and understood it. Thanks. I will do the necessary modifications in the header of the file.
Kind regards,
Marcos

2023-01-20 20:41 UTC, marcos-pereira commented on src/DQ.cpp
> +- Marcos da Silva Pereira (marcos.si.pereira@gmail.com)
Hello @juanjqo , I updated the header of the DQ.cpp with some of the contributions of each contributor. However, I tried to summarize the contributions from @mmmarinho and @bvadorno because they contributed several things. I based myself on the commit history. We will need to discuss how to write their contributions properly.

2023-01-23 08:01 UTC, juanjqo commented on src/DQ.cpp
> +1. Bruno Vilhena Adorno (adorno@ieee.org)
Hi @marcos-pereira, as you pointed out, there are a lot of contributions. Therefore, let's start a draft version of the contributions with only high-level descriptions instead of specific ones. For instance, 

```txt
1. Bruno Vilhena Adorno (adorno@ieee.org)
        - Responsible for the original implementation.
          [bvadorno committed on Jul 20, 2012](7368f3e)
          (https://github.com/dqrobotics/cpp/commit/7368f3ea3d557834661d723adde981250db0b87f).

2. Mateus Rodrigues Martins (martinsrmateus@gmail.com)
        - Added new methods, and support for Boost library.
          [mateusmartins committed on Jul 27, 2012]()
          (https://github.com/dqrobotics/cpp/commit/7d96efb354ffa07a093d5cb3f34af2c7ce8e2d39).


3. Murilo M. Marinho (murilo@nml.t.u-tokyo.ac.jp)
       - Refactoring, and compliance with the new style. 
         [murilomarinho committed on Dec 22, 2012](c7f4596)
         (https://github.com/dqrobotics/cpp/commit/c7f459612bb47ab2151b64ed6820c9f6fb242fa6).

       - Added support for Eigen library
         [murilomarinho committed on Jan 31, 2013](1ec0bf0)
         (https://github.com/dqrobotics/cpp/commit/1ec0bf096ff7b9f3f73ee0513f0a6f07c2a58f01).

4. Marcos da Silva Pereira (marcos.si.pereira@gmail.com)
        - Translated the Q4 and the Q8 methods from the MATLAB implementation in PR #56 
          (https://github.com/dqrobotics/cpp/pull/56).
```

2023-01-23 08:04 UTC, juanjqo commented on src/DQ.cpp
>      along with DQ Robotics.  If not, see <http://www.gnu.org/licenses/>.
@marcos-pereira, please update the year of the copyright in both `DQ.cpp` and `DQ.h`.  
From:
```txt
(C) Copyright 2011-2020 DQ Robotics Developers
```
To:
```txt
(C) Copyright 2011-2023 DQ Robotics Developers
```

2023-01-23 08:17 UTC, juanjqo commented on src/DQ.cpp
> +* @returns Return the partial derivative of the unit dual quaternion x with respect to log(x).
@marcos-pereira, please update the documentation to match the DQ::Q4() description. 
From:
```txt
@returns Return the partial derivative of the unit dual quaternion x with respect to log(x).
```
To:
```txt
@returns A matrix representing the desired partial derivative.
```

2023-02-17 19:00 UTC, marcos-pereira commented on src/DQ.cpp
> +1. Bruno Vilhena Adorno (adorno@ieee.org)
Done in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/93e0a8055d49b8cbd3961eb8747289f5a5ac2d82) and in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/38066e9a5aee16ad6e5143678ebd5353e8623b3e).

2023-02-17 19:00 UTC, marcos-pereira commented on src/DQ.cpp
> +* @returns Return the partial derivative of the unit dual quaternion x with respect to log(x).
Done in [this commit]([38066e9](https://github.com/dqrobotics/cpp/pull/56/commits/38066e9a5aee16ad6e5143678ebd5353e8623b3e)).

2023-02-17 19:04 UTC, marcos-pereira commented
Hi @juanjqo , I have done the proposed modifications and committed them. 

Sorry for the long delay, but something else got in the way.

Is there any other modification we have to do for this PR?

2023-02-22 09:51 UTC, juanjqo commented on src/DQ.cpp
> +* @returns @returns A matrix representing the desired partial derivative.
@marcos-pereira, please remove the duplicate `@returns` in the documentation of `Matrix<double,8,6> DQ::Q8() const`. This is, please update the line

```cpp
@returns @returns A matrix representing the desired partial derivative.
```
To

```cpp
@returns A matrix representing the desired partial derivative.
```

2023-02-22 09:54 UTC, juanjqo commented
> Hi @juanjqo , I have done the proposed modifications and committed them.
> 
> Sorry for the long delay, but something else got in the way.
> 
> Is there any other modification we have to do for this PR?

Hi @marcos-pereira, thank you for your effort. Almost there!

2023-02-22 23:05 UTC, marcos-pereira commented on src/DQ.cpp
> +* @returns @returns A matrix representing the desired partial derivative.
Sorry for the typo! Typo fixed in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/afaaec1d6e6acb5cc5a83fb7a6e8357cada131ce).

Let me know if anything else must be fixed.

2023-02-23 06:35 UTC, juanjqo commented on src/DQ.cpp
> +* @returns @returns A matrix representing the desired partial derivative.
Thanks @marcos-pereira, 
I think it's all on my side.

2023-02-23 06:37 UTC, juanjqo approved these changes
Hi @mmmarinho and @bvadorno 

I think this PR is ready for your comments!

Best regards, 

Juancho

2023-02-25 07:29 UTC, mmmarinho commented
@juanjqo 

Thanks! Can you click the `Resolve conversation` for all topics in your review that you think are already done? I can start mine after that.

2023-02-27 01:05 UTC, juanjqo commented
@mmmarinho,

The `Resolve conversation` is missing for me. I do not know if I need to enable it in some way. According to [Github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request), I need to have write access to do so. Do I have write access?


_"You can resolve a conversation in a pull request if you opened the pull request or if you have write access to the repository where the pull request was opened"_.

Best regards,

2023-02-27 08:51 UTC, bvadorno commented
> @mmmarinho,
> 
> The `Resolve conversation` is missing for me. I do not know if I need to enable it in some way. According to [Github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request), I need to have write access to do so. Do I have write access?
> 
> _"You can resolve a conversation in a pull request if you opened the pull request or if you have write access to the repository where the pull request was opened"_.

Hi @juanjqo,

I changed your access permissions. You should have write privileges now. 

All the best
Bruno

2023-02-27 09:01 UTC, juanjqo commented
Thanks @bvadorno!

@mmmarinho I resolved the conversations.

2023-02-27 13:50 UTC, mmmarinho requested changes
@marcos-pereira @juanjqo 
Please check my comments, nothing major.

2023-02-27 13:50 UTC, mmmarinho commented on src/DQ.cpp
> +    Vector4d r = this->vec4();
Everything that isn't changed afterwards, use the `const` modifier.

`const Vector4d r`

2023-02-27 13:50 UTC, mmmarinho commented on src/DQ.cpp
> +* @brief This method returns the partial derivative of a unit quaternion with respect to its logarithm.
It says unit quaternion here but you're not checking it explicitly like you are for `DQ::Q8`, why?

2023-02-27 14:31 UTC, marcos-pereira commented on src/DQ.cpp
> +    Vector4d r = this->vec4();
Fixed in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/0623aa3b1fc863d3251da0a0ad25e295cdfda1a0).

2023-02-27 14:31 UTC, marcos-pereira commented on src/DQ.cpp
> +* @brief This method returns the partial derivative of a unit quaternion with respect to its logarithm.
Hi @mmmarinho , you have a good point. I translated the method from the [MATLAB implementation](https://github.com/dqrobotics/matlab/blob/master/%40DQ/Q8.m) and it does not check if the quaternion has unit norm. Since you pointed that out, I added the unit norm check in the C++ implementation in [this commit](https://github.com/dqrobotics/cpp/pull/56/commits/0623aa3b1fc863d3251da0a0ad25e295cdfda1a0).

2023-02-28 03:01 UTC, juanjqo commented on src/DQ.cpp
> +* @brief This method returns the partial derivative of a unit quaternion with respect to its logarithm.
Hi @marcos-pereira,

In the current Matlab implementation,  (please @bvadorno correct me if I'm wrong) the method Q4() is not exposed to the user and is only used by Q8(). Furthermore, Q4() is called after checking the unit norm, therefore, there is no need to recheck it in Q4().

2023-03-04 01:25 UTC, mmmarinho commented on src/DQ.cpp
> +* @brief This method returns the partial derivative of a unit quaternion with respect to its logarithm.
On hold until https://github.com/dqrobotics/matlab/pull/91 is merged.

2023-04-03 09:59 UTC, mmmarinho commented on src/DQ.cpp
> +* @brief This method returns the partial derivative of a unit quaternion with respect to its logarithm.
@marcos-pereira @juanjqo 
The issue above has been merged, so please fix the CPP according to the latest MATLAB version.

2023-04-03 13:51 UTC, mmmarinho commented
@marcos-pereira @juanjqo 

Please check the code for compliance with the merged version. For example, is the `is_quaternion` condition missing? 

Don’t forget to add the tests for `Q4` which was the trigger for the changes in MATLAB.

2023-04-07 15:35 UTC, mmmarinho approved these changes

2023-04-07 15:38 UTC, mmmarinho commented
@marcos-pereira @juanjqo 

All indicates that `Q4` and `Q8` pass the tests in Python so I'll merge this into the master of CPP so that you can start using it. This is conditioned on the checks automatic tests running successfully.

If https://github.com/dqrobotics/python-tests/pull/6 turns out to be a bigger problem I'll reopen this issue.

2023-04-07 16:26 UTC, merged

2023-04-07 16:27 UTC, mmmarinho commented
Fix #55