This PR fixes issue 59 of the Python version of the DQ Robotics
dqrobotics/cpp pull request #67
Opened 2024-07-31 13:34 UTC by juanjqo

@dqrobotics/developers 

Hi @mmmarinho, 

This PR initializes some variables to match the Matlab implementation. Specifically, I initialized the attributes `damping`, `gain`, `system_reached_stable_region_`,  `stability_threshold`, `stability_counter`, and `stability_counter_max` of the class `DQ_KinematicController`. 

Furthermore, I added a default damping in the constructor of the class `DQ_ClassicQPController` to match the implementation of the class `DQ_ClassicQPController.m`.

### Minimal Example

```cpp
#include <iostream>
#include <dqrobotics/robots/KukaLw4Robot.h>
#include <dqrobotics/robot_control/DQ_ClassicQPController.h>
#include <dqrobotics/solvers/DQ_PROXQPSolver.h>

using namespace DQ_robotics;

int main()
{
    auto robot = std::make_shared<DQ_SerialManipulatorDH>(KukaLw4Robot::kinematics());
    auto solver = std::make_shared<DQ_PROXQPSolver>();
    auto controller = DQ_ClassicQPController(robot, solver);
    auto damping = controller.get_damping();
    std::cout<<damping<<std::endl;
}

```

### Output

```shell
0.001
```

### Output of the current version of DQ Robotics (MacOS)
```shell
0
```

Please let me know if additional modifications are required.

Best regards, 

Juancho

2024-08-01 15:56 UTC, mmmarinho requested changes
Thanks, @juanjqo. My major concern is the re-initialization of things already being initialized in the constructor.

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    double gain_{0};
@juanjqo Most of these were already being initialised, see below. It's probably better just to stick to only changing the damping.

https://github.com/dqrobotics/cpp/blob/2751d386951e525258eaf5e4673778f557a81371/src/robot_control/DQ_KinematicController.cpp#L54-L68

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    double damping_{0};
Maybe just add the initialisation in the constructor, together with everything else.

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    bool system_reached_stable_region_{false};
Same

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    double stability_threshold_{0};
Same

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    int stability_counter_{0};
Same

2024-08-01 15:56 UTC, mmmarinho commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    int stability_counter_max_{10};
Same

2024-08-01 15:56 UTC, mmmarinho commented on src/robot_control/DQ_ClassicQPController.cpp
> +    set_damping(1e-3); // Default damping.
If in the MATLAB version it's being initialized here, than that's fine. It could also be initialized in the parent class instead, together with everything else.

2024-08-03 10:55 UTC, bvadorno commented on src/robot_control/DQ_ClassicQPController.cpp
> +    set_damping(1e-3); // Default damping.
Dear @juanjqo and @mmmarinho,

MATLAB and C++ must always follow the same pattern unless there is a sensible reason for divergence. I agree with @mmmarinho that things shouldn't be reinitialized unless there is a sensible reason for doing so, which must be duly explained in the code.

@juanjqo, if you follow Murilo's suggestion, will the MATLAB and C++ codes match?

Kind regards,
Bruno

2024-09-13 09:22 UTC, juanjqo commented on src/robot_control/DQ_ClassicQPController.cpp
> +    set_damping(1e-3); // Default damping.
@mmmarinho you're right, the attributes are being initialized in the constructor.  In Matlab, the damping is initialized in the parent class (damping = 0). In the `DQ_ClassicQPController` class, however, the damping is set to 1e-3. 

@bvadorno no, they do not match. Unlike the C++ implementation, the Matlab version of `DQ_KinematicController.m` does not initialize the attributes in the constructor. Instead, they are defined directly in the class. Furthermore, the constructor is public in `DQ_KinematicController.m` and protected in `DQ_KinematicController.h`

Matlab: 

```matlab
classdef DQ_KinematicController < handle
    properties (Access=protected)
        gain = 0.0;
    end
    function obj = DQ_KinematicController(robot)
            if ~isa(robot,'DQ_Kinematics')
                error('DQ_KinematicController expects a DQ_Kinematics object');
            end
            obj.robot = robot;
            obj.last_control_signal = zeros(robot.get_dim_configuration_space(),1); 
     end
end
```
C++:
 
```cpp
// header
class DQ_KinematicController
{
protected:
    double gain_;
    DQ_KinematicController(const std::shared_ptr<DQ_Kinematics>& robot);
    DQ_KinematicController();
}

//source
DQ_KinematicController::DQ_KinematicController(const std::shared_ptr<DQ_Kinematics> &robot):
    DQ_KinematicController()
{
    robot_sptr_ = robot;
}
DQ_KinematicController::DQ_KinematicController():
    gain_(0.0),
{

}
    
```

PS. @bvadorno, In one of our internal DQ robotics meetings, we decided to modify the Matlab version to match the C++ one. This is, initializing the attributes in the constructor. May I follow that plan?

Best regards, 

Juancho

2024-09-16 12:21 UTC, mmmarinho commented
Hi @juanjqo and @bvadorno ,

I'm quoting the reply by @juanjqo  here because if we resolve that conversation all the discussion will be lost (AFAIK).

> @bvadorno no, they do not match. Unlike the C++ implementation, the Matlab version of `DQ_KinematicController.m` does not initialize the attributes in the constructor. Instead, they are defined directly in the class. Furthermore, the constructor is public in `DQ_KinematicController.m` and protected in `DQ_KinematicController.h`

> PS. @bvadorno, In one of our internal DQ robotics meetings, we decided to modify the Matlab version to match the C++ one. This is, initializing the attributes in the constructor. May I follow that plan?

If I may add to this discussion, given that I wasn't part of those meetings.

A bazillion years ago (more accurately 12 years or so), the C++ library had a C++98-ish style, hence in-class initialization was not possible. Please put into context that it inherited from even earlier and C++11 compilers were still not widespread. For instance,
https://github.com/dqrobotics/cpp/blob/ba29d7620af8258fd0dc8bb6a14dfa44a3cc63b7/DQ_kinematics.h#L17

In-class initialization has been added to compilers for [C++11 and beyond](https://isocpp.org/wiki/faq/cpp11-language-classes). In-class initialization is preferred in C++11 as well, no doubt. It leads to less repetition and could be less error-prone (if users are observant of the style). However, because constructor initialization isn't wrong, the original style was followed to keep the files consistent across the library (if we do in-class initialization somewhere, I'm sure it's rare).   

My initial point when flagging the in-class initialization of the damping factor was simply that the initialization must happen all in the same place. It's fine to move it out of the constructor and have all initialization done in class. It is also reasonable to move the new one to the constructor. What is confusing is to have part of it in class and part of it in the constructor.

2024-09-18 09:34 UTC, juanjqo commented on include/dqrobotics/robot_control/DQ_KinematicController.h
> +    double damping_{0};
@mmmarinho I removed all modifications in the class `DQ_KinematicController` since, as you pointed out, the attributes are being initialized in the constructor.

2024-09-23 15:43 UTC, bvadorno commented
Thanks for the additional context, @mmmarinho. Since I'm stuck with C++98, having the context of the functionalities that came after is always a mix of delight (learning cool things) and despair (feeling like a dinosaur).

@juanjqo, since both are correct, let's stick with what we decided in person. I don't remember the reason for our decision anymore, but I'm quite sure we had a good reason (we probably concluded that changing MATLAB would be easier).

Kind regards,
Bruno

2024-09-26 09:50 UTC, mmmarinho approved these changes
Hi @juanjqo,

From what I can see, the current implementation is following the MATLAB format while keeping to the C++ requirements. This seems good to go.

2024-09-26 09:50 UTC, mmmarinho commented on src/robot_control/DQ_KinematicController.cpp
> +    damping_(0),//Todo: change this inialization to use empty vector
This seems to be properly matching MATLAB.

https://github.com/dqrobotics/matlab/blob/74b5ffc535dd08724436713b9846fc9e54e03525/robot_control/DQ_KinematicController.m#L83

2024-09-26 09:50 UTC, mmmarinho commented on src/robot_control/DQ_ClassicQPController.cpp
> +    set_damping(1e-3); // Default damping.
This seems to be properly following MATLAB.

https://github.com/dqrobotics/matlab/blob/74b5ffc535dd08724436713b9846fc9e54e03525/robot_control/DQ_ClassicQPController.m#L37

2024-09-26 09:54 UTC, merged